### PR TITLE
Mixin methods return boolean results.

### PR DESCRIPTION
**Pull request by AntonTyutin**
`softDelete()`, `unDelete()` and `hardDelete()` methods return boolean results.

### CODE REVIEW

**Comment by AntonTyutin** [comment]
There is some unexpected failure in the CI build. I've no see any reason for that. Could you rerun build please?

**Comment by cornernote** [comment]
Thanks! I'll try fix the CI later

**Comment by AntonTyutin** [comment]
You should make a tag (`1.0.3`), so commit a new version for composer (packagist).

**Comment by cornernote** [comment]
Done!  I also pulled HVVM (can't be assed fixing the CI) and added PHP 7.1 to the CI.

**Pull request merged**
